mod replace_conditional_with_polymorphism_before;
mod replace_conditional_with_polymorphism_after_1;
mod replace_conditional_with_polymorphism_after_2;
mod replace_conditional_with_polymorphism_after_3;
mod replace_conditional_with_polymorphism_after_4;